source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BUKPickerView_Example', :exclusive => true do
  pod "BUKPickerView", :path => "../"
end

target 'BUKPickerView_Tests', :exclusive => true do
  pod "BUKPickerView", :path => "../"

  
end
